### ISSUE TITLE
inserter are not removed with CMs instant deconstruction 

### ISSUE THREAD

**Issue by 0ptera** [mspielberg/factorio-miniloader#1]
When used with CMs instant deconstruction cheat the hidden inserter are not removed.

**Comment by mspielberg** [comment]
I'm guessing this is a side-effect of the 0x0 selection_box that the hidden inserters have. Giving them a real selection_box would let Creative Mode's deconstruction planner pick them up, but they would also be picked up in blueprints. I could probably work around that, but I'm not entirely sure what the best approach there would be yet.

Probably the best thing would be for Creative Mode to raise an event, either on_robot_mined_entity or on_entity_died, which would allow the existing scripting to clean up the hidden inserters. I'll keep investigating this, since I haven't examined the Creative Mode code yet.

**Comment by mspielberg** [comment]
Interesting. Creative Mode raises the on_robot_pre_mined event, but not on_robot_mined_entity. Miniloader wants to return the items held by the invisible inserters to the player or robot doing the mining, which is only possible during on_robot_mined_entity and on_player_mined_entity.

I've raised the issue to Mooncat, and I hope Creative Mode will be fixed to better adhere to the contract of the game engine for entity removal.

For now I will close this issue, and if necessary I will reopen and try to add a workaround for this specific bug in Creative Mode. I can trap on_robot_pre_mined, but this will only have an effect on Creative Mode, not on standard gameplay, and I'd prefer not to add specific code to work around a Creative Mode bug if possible.
