### ISSUE TITLE
Rebalancing doesn't work?

### ISSUE THREAD

**Issue by Sraw** [mspielberg/factorio-miniloader#31]
I'm using the most basic mini loader on my bus and want to use it as a balancer. But it just changes the side of original items but doesn't really balance anything.

BTW, I'm using all bob's mods.

Is this a bug or expected behavior?

**Comment by dfht684** [comment]
I noticed similar items:

- In a bus, the blue miniloader tends to favor 1 side of input blue belt
- A mini loader pushing material to a 12 beacon assembler also favors 1 side of input blue belt

I ended up taking out the ones I used as a single lane balancer and putting in the 1to1 balancer.

I've not tested with the red or yellow miniloaders. I also didn't try this with the filtered level 3 miniloaders; since I primarily noticed this issue with the input side of the miniloader.

**Comment by mspielberg** [comment]
Miniloaders make no guarantees about the consistency of their “balancing.” They have two inserters which consume from the input belt and then place on different sides of the output belt.

If the input belt is significantly less than half-full, it’s likely that one inserter will consistently pick up all the items, and place them in a single lane on the output side.

If the input belt is full, such as when the output belt backs up, then the inserters will (as always) prefer to pick up from a single side of the input belt, and consumption from the input will not be balanced.

If the input belt has one lane full and the other empty, the two inserters will alternate picking up items, and the output belt is (usually) a balanced half-full belt. This is the only situation where miniloaders can be said to accurately rebalance a single belt.
