### ISSUE TITLE
3.75 speed chutes (Bob´s belt overhaul) load chests with up to 15 items/s

### ISSUE THREAD

**Issue by Cereal-Sam** [mspielberg/factorio-miniloader#62]
Using chutes to load chests results in them loading up to 15 items per second instead of 3.75.
Unloading seems to be fine.
The order of placing the chest/chute /splitter doesnt matter. A belt infront of the chute works aswell.
Placing them by hand/bot also seems to not matter.
![image](https://user-images.githubusercontent.com/62474527/128601439-89dc81ae-6353-4d99-9901-6ab210fa9523.png)

Edit: Seems to be not only a chute issue, miniloaders can load with up to 4x of their intended speed aswell.
Edit2: Inserter capacity tech seems to not affect it

**Comment by mspielberg** [comment]
This is difficult to avoid due to inserters immediately picking up items from the loader belt, meaning that a faster belt adjacent to the loader can push items in at its own rate, not the rate of the loader belt.

**Comment by modo-lv** [comment]
I did a similar test in Nullius, using the maximum speed belts, and the results were

* yellow loader -> chute = fully consumed
* red loader -> yellow loader = fully consumed
* blue loader -> red loader = belt fills up
* green loader -> blue loader = belt fills up

Why would inserters pick up something faster than they can put it down? The belts might be faster, but that only matters if the inserters inside the loader can move just as fast. If the chute actually contains 15/s inserters that are only slowed down by the belt, it's either a bug or an intended feature, which would be nice to see in a tooltip (instead of discovering it by accident when placing mismatched loaders/chutes).

**Comment by mspielberg** [comment]
I used to try to match inserter speeds to the belt speeds, but no longer, because it was an unending stream of people complaining that this one was just a hair too fast, and this one a hair too slow, and it would vary based on inserter timing. It was too much trouble so I switched to having only the belts being the throughput limit. If you want to cheat by using a loader at a faster speed than intended, you’re free to do so.

**Comment by modo-lv** [comment]
I don't mind the speed difference and don't intend to cheat, but at first I just thought that maybe that's the intended functionality. Then I thought maybe it's a bug, so I came here to report it, but found this issue already here. Others might keep discovering this discrepancy and asking the same questions and making the same bug reports. I think it would be helpful if the possible speed difference was mentioned in tooltip or an FAQ or something.
