### ISSUE TITLE
1.15.3 - Lane configuration is unintuitive

### ISSUE THREAD

**Issue by Spanfile** [mspielberg/factorio-miniloader#69]
I think the lane separation feature is great, but there's an issue: when using an output filter loader or an output loader connected to a circuit network, configuring filters / circuit conditions requires manually setting the filter / circuit condition on both lanes, and there's no (at least obvious) way of copying the configuration to the other lane after setting it on one. This is error-prone, unintuitive and tedious, having to remember to configure both lanes when previously everything else worked with just one configuration. I think there should be an extra option (where the lane switch currently is) to opt-in to the lane separation. With the option not set (and it wouldn't be set by default), the filter / circuit condition operate on both lanes as it previously did. Setting it would lead to the current function.

Additionally as a purely stylistic suggestion, the configuration pane for the lane could be made similar to the vanilla circuit and logistic network configuration panes, or for example the mod Even Distribution, where the configuration pane is toggleable with a button and it opens to the right side of the inventory screen.

**Comment by mspielberg** [comment]
I agree with your suggestion that there should an option to by default link the settings to both lanes together.

I tried having the additional configuration UI on the right-hand side of the vanilla UI, but there is no way to stack it below the existing circuit/logistic connection UI that already appears on the right. This leads to what I feel is an overly dramatic variation of the width of the UI. This is less of a problem with Even Distribution and the character inventory, since the character inventory does not have an optional vanilla panel that appears and disappears on the right.

**Comment by mspielberg** [comment]
Done in v1.15.4.
